<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerErxxFOg\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerErxxFOg/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerErxxFOg.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerErxxFOg\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerErxxFOg\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'ErxxFOg',
    'container.build_id' => '72b97ec9',
    'container.build_time' => 1626903731,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerErxxFOg');
